Repository plantineers/plantbuddy-server, pull requests merged in 2023-06, with the labels that each got.

#70 feat: add /plant-groups/overview endpoint #69
  api.yaml
  cmd/main.go
  plant/plant-group-database.go
  plant/plant-group-sqlite.go
  plant/plant-groups-endpoint.go
  plant/plant-model.go
  server-requests.http
Labels: enhancement

#67 fix: plant-group creation
  cmd/main.go
  go.mod
  go.sum
  plant/plant-endpoint.go
  plant/plant-group-endpoint.go
  plant/plant-group-sqlite.go
  plant/plant-model.go
  plant/validator.go
  sensor/sensor-model.go
Labels: bug

#72 feat: workflow for releases #57
  .github/workflows/go-push.yml
  .github/workflows/go-release.yml
  README.md
Labels: enhancement

#73 feat: sensor-data endpoint query parameters
  sensor/sensor-data-endpoint.go
  sensor/sensor-data-sqlite.go
  sensor/sensor-model.go
  server-requests.http
Labels: bug, enhancement

#77 feat: enforce authentication on all endpoints
  auth/user-authentication-middleware.go
  cmd/main.go
  server-requests.http
Labels: enhancement
